image: debian:jessie

stages:
  - build

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/baffolobill/boost:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: boost:debian

build:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" registry.gitlab.com
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE:jessie ./debian/
    - docker push $CONTAINER_TEST_IMAGE:jessie
    - docker build -t $CONTAINER_TEST_IMAGE:xenial ./ubuntu/
    - docker push $CONTAINER_TEST_IMAGE:xenial
  only:
    - master
